SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK_SALES
JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE SALES_DATE>= '2022-01-01' AND SALES_DATE<='2022-01-31'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC, CATEGORY DESC