SELECT PRODUCT_CODE, OS.SA * PRICE AS SALES
FROM PRODUCT
JOIN (
    SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS SA
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID
) AS OS ON PRODUCT.PRODUCT_ID = OS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC