SELECT C.CAR_ID, C.CAR_TYPE, C.FEE
FROM (
    SELECT B.CAR_ID, B.CAR_TYPE, ROUND((B.DAILY_FEE*(100-DISCOUNT_RATE))/100*30,0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS B
    LEFT JOIN (
        SELECT CAR_TYPE,DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE='30일 이상'
    ) AS A
    ON B.CAR_TYPE = A.CAR_TYPE
    WHERE CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (START_DATE<DATE('2022-11-01') AND END_DATE<DATE('2022-11-01'))
            AND NOT (START_DATE>DATE('2022-11-30') AND END_DATE>DATE('2022-11-30'))
    ) AND B.CAR_TYPE IN ('SUV', '세단') 
) AS C
WHERE C.FEE>=500000 AND C.FEE <= 2000000
ORDER BY C.FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC

