-- 코드를 입력하세요
SELECT REST_INFO.FOOD_TYPE, REST_ID, REST_NAME, A.FAVORITES
FROM REST_INFO
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE  
) AS A ON REST_INFO.FOOD_TYPE=A.FOOD_TYPE AND REST_INFO.FAVORITES=A.FAVORITES
ORDER BY REST_INFO.FOOD_TYPE DESC