-- 코드를 입력하세요
SELECT A.CAR_ID, A.AVERAGE_DURATION
FROM (
    SELECT CAR_ID, ROUND(AVG(B.DATE), 1) AS AVERAGE_DURATION
    FROM (
        SELECT CAR_ID, DATEDIFF(END_DATE,START_DATE)+1 AS DATE
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) AS B
    GROUP BY CAR_ID
    ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC
) AS A
WHERE A.AVERAGE_DURATION>=7