SELECT DATE_FORMAT(SALES_DATE, "%Y") AS YEAR, DATE_FORMAT(SALES_DATE, "%m") AS MONTH, COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PURCHASED_USERS, ROUND( COUNT(DISTINCT ONLINE_SALE.USER_ID) / T.total_users, 1) AS PURCHASE_RATIO
FROM ONLINE_SALE
JOIN USER_INFO ON ONLINE_SALE.USER_ID=USER_INFO.USER_ID
JOIN (
    SELECT COUNT(*) AS total_users
    FROM USER_INFO
    WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31') AS T
WHERE JOINED BETWEEN '2021-01-01' AND '2021-12-31'
GROUP BY DATE_FORMAT(SALES_DATE, "%Y-%m")
ORDER BY YEAR, MONTH;