SELECT A.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, (A.AMOUNT * FOOD_PRODUCT.PRICE) AS TOTAL_SALES
FROM (
    SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022.05.01' AND '2022.05.31'
    GROUP BY PRODUCT_ID) AS A
JOIN FOOD_PRODUCT ON A.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID ASC