SELECT MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE 
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE ON R.MEMBER_ID = MEMBER_PROFILE.MEMBER_ID
WHERE R.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE ASC, R.REVIEW_TEXT ASC