SELECT i.ITEM_ID, i.ITEM_NAME, i.RARITY
FROM ITEM_INFO AS i
RIGHT JOIN (
SELECT ITEM_TREE.ITEM_ID
FROM ITEM_INFO 
JOIN ITEM_TREE ON ITEM_INFO.ITEM_ID=ITEM_TREE.PARENT_ITEM_ID
WHERE ITEM_INFO.RARITY = "RARE" ) AS ib ON ib.ITEM_ID = i.ITEM_ID
ORDER BY i.ITEM_ID DESC