SELECT DISTINCT DEVELOPERS.ID, DEVELOPERS.EMAIL, DEVELOPERS.FIRST_NAME, DEVELOPERS.LAST_NAME
FROM DEVELOPERS
JOIN SKILLCODES ON DEVELOPERS.SKILL_CODE & SKILLCODES.CODE > 0  
WHERE SKILLCODES.NAME IN ('Python', 'C#')
ORDER BY DEVELOPERS.ID ASC