SELECT b.YEAR, b.M-a.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA AS a
LEFT JOIN (
    SELECT MAX(SIZE_OF_COLONY) AS M, EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY EXTRACT(YEAR FROM DIFFERENTIATION_DATE)
) AS b ON EXTRACT(YEAR FROM a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY b.YEAR ASC, YEAR_DEV ASC