SELECT FOOD_PRODUCT.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
    ORDER BY PRICE ASC
) AS A ON FOOD_PRODUCT.CATEGORY = A.CATEGORY AND FOOD_PRODUCT.PRICE = A.MAX_PRICE
ORDER BY MAX_PRICE DESC